# fly.toml app configuration file generated for kindline-care on 2026-04-25T09:00:26Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kindline-care'
primary_region = 'jnb'

# Tigris storage: dry-sun-4981

[deploy]
  strategy = 'immediate'
  release_command = 'npx prisma@5.22.0 db push --accept-data-loss --skip-generate'

[env]
  PORT = '3000'

[build]
  [build.args]
    NEXT_PUBLIC_SUPABASE_URL = "https://ellswjqkvfcgiaqjuvkn.supabase.co"
    NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_N9I8ETunkIdn-OISr-daRA_NWAJ8Ekx"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[mounts]]
  source = 'kindline_care_data'
  destination = '/data'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1gb'
